name: CD

on:
    push:
        branches:
        - main
        paths:
        - 'infrastructure/**'
        - 'src/**'
        - 'scripts/**'
        - 'Cargo.toml'
        - '.github/workflows/cd.yml'


jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Install Rust
          uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
            override: true
        - name: Build Lambda functions
          run: python3 ./scripts/build.py
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}
        - name: Init Tofu
          run: tofu -chdir=infrastructure init
        - name: Plan Tofu
          env:
            TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            TF_VAR_AWS_REGION: ${{ secrets.AWS_REGION }}
          run: tofu -chdir=infrastructure plan
        - name: Apply Tofu
          env:
            TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            TF_VAR_AWS_REGION: ${{ secrets.AWS_REGION }}
          run: tofu -chdir=infrastructure apply -auto-approve
